### ISSUE TITLE
Encryption and checksums for downloads

### ISSUE THREAD

**Issue by DFyson** [osmandapp/OsmAnd-misc#101]
I was trying to download a nightly and somehow I downloaded it 'successfully' 5 times getting 5 different MD5 sums which was very strange. Would is be possible to include checksums alongside the downloads? Aswell, now that website encryption certificates [are free](https://letsencrypt.org/), why not use TLS encryption? Both are pretty standard for minimizing risks such corruption and man in the middle tampering.

**Comment by vshcherb** [comment]
We have separate issue for HTTPS, we are about to switch but that requires extra preparation to switch live servers.
