### ISSUE TITLE
Western-Sahara map not translated

### ISSUE THREAD

**Issue by aceman444** [osmandapp/OsmAnd-misc#128]
In the list of map regions to download inside OsmAnd 3.0, it seems "Africa Western-sahara" map is not translated.
However there is Western Sahara data in the file
https://raw.githubusercontent.com/osmandapp/OsmAnd-misc/master/osm-planet/osm-data/countries_admin_level_2.osm

So maybe just the relation 2559126 is not properly linked to the map file name?

**Comment by xmd5a2** [comment]
Fixed

**Comment by aceman444** [comment]
Thanks. Fix in commit 0b2156f4f2b0c2ffa558c98abf21dbbf715e036d .
