### ISSUE TITLE
osmand.net and other subdomains lack IPv6

### ISSUE THREAD

**Issue by juliaszone** [osmandapp/OsmAnd-misc#144]
Hi,
I've found out that osmand.net and many of the subdomains including the download servers lack IPv6 in DNS. I have compiled a list of hosts below using crt.sh.
It would be very worthwhile to work this up, as IPv6 adoption is progressing globally and it has become the dominant protocol in many countries - with a steadily increasing trend.
Some ISPs are already starting to ditch the legacy protocol (IPv4) and some just cannot bother or afford to deal with it. It's getting harder and harder to obtain IPv4 blocks.
If necessary, I can provide links to resources, statistics, answers to questions and some help.

**Hetzner Online GmbH** (Support IPv6)
- 88.198.46.27, hosting: docs.osmand.net, osmand.net, download.osmand.net, www.osmand.net, translate.osmand.net
- 88.198.16.57, hosting: dl2.osmand.net
- 168.119.14.41, hosting: mapnik.osmand.net, tile.osmand.net, maptile.osmand.net
- 213.239.209.5, hosting: dl3.osmand.net
- 148.251.126.25, hosting: test.osmand.net, creator.osmand.net
- 167.235.1.175, hosting: dl4.osmand.net

**Scaleway** (Seem to support IPv6, atleast partially)
- 51.159.29.78, hosting: dl9.osmand.net
- 51.159.29.76, hosting: dl8.osmand.net

**Comment by vshcherb** [comment]
Added to the plan list

**Comment by juliaszone** [comment]
Cool! I don't know whether there are some other subdomains or domains missing, it would be best if someone with zonefile access or someone who knows of it checks that too.

**Comment by RZR-UA** [comment]
done

**Comment by vshcherb** [comment]
How to test.

**Comment by vshcherb** [comment]
```for d in maptile creator download dl2 dl3 dl4 dl8 dl9; do echo $d; curl -6 -sk "https://$d.osmand.net/download?self=true&file=World_altitude_correction_WW15MGH.extra.zip" | md5sum;  done
```
